import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The redlines, read from the committed artefact `review/corrections.json`.
 *
 * Generated by `tools/gen-corrections.mjs`, which walks git. It is READ rather than recomputed for
 * the same reason `lib/history.ts` is: `git log` is not available to a Next page and would be wrong
 * if it were, because Vercel clones shallow and a shallow walk finds fewer prior values — a
 * correction would silently render as having no before.
 *
 * **A missing file is not zero corrections**, and the page distinguishes them.
 */
export type Redline = {
  id: string;
  layer: 'ledger' | 'provenance';
  field: string;
  title: string;
  quote: string;
  before: string;
  after: string;
  beforeDate: string;
  afterDate: string | null;
  afterSubject: string | null;
  /** `prefix + removed + suffix === before` and `prefix + added + suffix === after`, exactly. */
  prefix: string;
  removed: string;
  added: string;
  suffix: string;
};

const FILE = join(process.cwd(), 'review', 'corrections.json');

export const redlines: Redline[] = (() => {
  if (!existsSync(FILE)) return [];
  try {
    return (JSON.parse(readFileSync(FILE, 'utf8')).entries ?? []) as Redline[];
  } catch {
    return [];
  }
})();

export const redlinesExist = existsSync(FILE);
